#!/bin/bash
# If you're using my script, all you need to do is edit the following lines to work for you.
# Final zip will exist in "build" as "furnace-1.0.0-aosp_hammerhead.zip" for example
# If you are using a non-appended dt.image, you will need to add "--dt path/to/dt.img" and
# the appropriate lines for dtbTool to compile it, if not prebuilt.
build=/home/yoshishapow/Paradox_Builds
kernel="test"
version="1.0.0"
variant="falcon"
# ramdisk=none
toolchain=/home/yoshishapow/linaro_toolchain/bin
toolchain2="arm-eabi-"
config="msm8226_mmi_defconfig"
kerneltype="zImage-dtb"
jobcount="-j8"
ps=2048
base=0x00000000
ramdisk_offset=0x01000000
tags_offset=0x00000100
cmdline="console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 vmalloc=400M utags.blkdev=/dev/block/platform/msm_sdcc.1/by-name/utags androidboot.write_protect=0 zcache androidboot.selinux=permissive"

export ARCH=arm
export CROSS_COMPILE=$toolchain/"$toolchain2"
make "$config"
# Export script by Savoca
